from numbers import Integral
import pyautogui as py
import pyautogui
import pytesseract as ocr
from PIL import Image
import PIL.Image
import time
import pygetwindow
import pyodbc
import pyttsx3
import tkinter as tk
from tkinter import messagebox
from tkinter import *
from tkinter import ttk

#Instanciando Tkinter e criando interface de usuário
window = tk.Tk()
window.title('RPA com AI HCTCO')
window.geometry('400x300')
#Recurso que impede que o usuário redimensione a janela
window.resizable(width=False, height=False)
w = Label(window, text='Escolha entre as opções abaixo: ', font=35)
w.place(x=90, y=10)

Checkbutton1 = IntVar()
Checkbutton2 = IntVar()

#Recurso que impossibilita que dois CheckButtons sejam selecionados ao mesmo tempo.
def clear2():
    Checkbutton2.set(0)

def clear1():
    Checkbutton1.set(0)

#CheckBox da Interface do App 
btn1 = Checkbutton(window, text="Baixa", variable=Checkbutton1, onvalue=1, offvalue=0, height=2, width=10, command=clear2)
btn2 = Checkbutton(window, text="Controle de Recebimentos", variable=Checkbutton2, onvalue=1, offvalue=0, height=2, width=20, command=clear1)


btn1.place(x=105, y=55)
btn2.place(x=126, y=85)

textoPeriodo = Label(window, text="Período: ", bg="#d3d3d3")
textoPeriodo.place(x=10, y=200)
entradaPeriodoMes = Entry(window)
entradaPeriodoMes.place(x=60, y=200, width=15)
barra = Label(window, text="/", bg="#d3d3d3")
barra.place(x=75, y=200)
entradaPeriodoAno = Entry(window)
entradaPeriodoAno.place(x=85, y=200, width=30)

textoConvenio = Label(window, text="Convenio: ", bg="#d3d3d3")
textoConvenio.place(x=150, y=200)
caixaSelecao = ttk.Combobox(window, values=[
    "AMIL",
    "ASSIM",
    "BRADESCO",
    "CAC",
    "CEF",
    "CORPO DE BOMBEIROS DO ESTADO DO RIO DE JANEIRO",
    "FUSMA",
    "GOLDEN CROSS",
    "MEDISERVICE",
    "PETROBRAS",
    "POSTAL SAUDE",
    "SUL AMERICA",
    "UNIMED"
])
caixaSelecao.place(x=210, y=200, width=170)

labelFatura = Label(window, text="Ordem da Fatura: ", bg="#d3d3d3")
labelFatura.place(x=10 ,y=240)
entradaOrdemFatura = Entry(window)
entradaOrdemFatura.place(x=110, y=240, width=30)

textoUnidade = Label(window, text="Unidade: ", bg="#d3d3d3")
textoUnidade.place(x=160, y=240)
caixaUnidade = ttk.Combobox(window, values=[
    "AMBULATÓRIO (FATURAMENTO)",
    "HOSPITAL DAS CLÍNICAS DE TERESÓPOLIS",
    "MATERNIDADE DO HCTCO (FATURAMENTO)"
])
caixaUnidade.place(x=211, y=240, width=170)


#Aviso de recurso não disponível
def baixa():
    messagebox.showwarning("Recurso Futuro", "O Recurso Selecionado Ainda está sendo desenvolvido e estará disponível em breve. Fique tranquilo, nós avisaremos.")


dados_conexao = ('DRIVER={Devart ODBC Driver for Oracle};Host=10.1.0.137;Port=1521;SID=DBFESOCONS;UID=GTIC_078463;Password=gtic_sup23_078463;Direct=True')
#Rotina de automação a ser executada
def automacao():
    inicio = time.time()
    py.alert("Atenção! A automação está sendo iniciada.")
    py.PAUSE = 1.2
    res = py.size()
    print(res)
    if res.width == 1366 and res.height == 768:
        try:
            #Acessar onde ficam os dados a serem obtidos
            py.moveTo(784, 26)
            py.click()
            py.moveTo(782, 142)
            py.click()
            title = "Controle de Recebimentos"
            window = pygetwindow.getWindowsWithTitle(title)[0]
            contador1 = 0
            if window.title == "Controle de Recebimentos (RDESKAMB.UNIFESO.LAN)":
                contador1 = contador1 + 1
                py.moveTo(573, 697)
                py.click()
                #Selecionar mês dos resultados
                py.moveTo(325, 392)
                py.click()
                py.write(entradaPeriodoMes.get() + entradaPeriodoAno.get())
                py.moveTo(525, 396)
                py.click()
                #Convenio
                if caixaSelecao.get() == "AMIL":
                    codPlano = 5 
                    py.moveTo(589, 416)
                    py.click()
                elif caixaSelecao.get() == "ASSIM":
                    codPlano = 7
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "BRADESCO":
                    codPlano = 27
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "CAC":
                    codPlano = 10
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "CEF":
                    codPlano = 1151
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "CORPO DE BOMBEIROS DO ESTADO DO RIO DE JANEIRO":
                    codPlano = 2879
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "FUSMA":
                    codPlano = 5383
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "GOLDEN CROSS":
                    codPlano = 20
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "MEDISERVICE":
                    codPlano = 24
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "PETROBRAS":
                    codPlano = 26
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "POSTAL SAUDE":
                    codPlano = 4113
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')
                elif caixaSelecao.get() == "SUL AMERICA":
                    codPlano = 31
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    if entradaPeriodoMes.get() == '02' and entradaPeriodoAno.get() == '2021':
                        py.press('up')
                    py.press('enter')
                elif caixaSelecao.get() == "UNIMED":
                    codPlano = 4131
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('down')
                    py.press('enter')

                py.moveTo(699, 388)
                py.click()
                if caixaUnidade.get() == "HOSPITAL DAS CLÍNICAS DE TERESÓPOLIS":
                    codHospital = 3
                    py.moveTo(836, 427)
                    py.click()
                elif caixaUnidade.get() == "AMBULATÓRIO (FATURAMENTO)":
                    codHospital = 13
                    py.moveTo(802, 410)
                    py.click()
                elif caixaUnidade.get() == "MATERNIDADE DO HCTCO (FATURAMENTO)":
                    codHospital = 14
                    py.moveTo(819, 438)
                    py.click()

                py.moveTo(914, 393)
                py.click()

            else:
                py.alert("A janela de Recebimentos não startou. Encerrando...")
                exit()

        except KeyboardInterrupt as kex:
            print("Programa encerrado pelo usuário via teclado.")
            exit()
        except:
            print("Resolução de tela não cadastrada no sistema")
            exit()
    else:
        py.alert("Resolução de tela não cadastrada. Encerrando...")
        exit()

    #Gerador de repetições
    conexao = pyodbc.connect(dados_conexao)
    cursor = conexao.cursor()
    time.sleep(10)
    im3 = pyautogui.screenshot(f'db/image.png', region=(337,436,31,15))
    time.sleep(4)
    def reconhecimento():
        #phrase2 = ocr.image_to_string(PIL.Image.open('db/image.png'), lang='por')
        #print(int(phrase2))
        cursor.execute(f"SELECT count(A.NUMEROLOTE) FROM SZFATURACONVENIO A WHERE A.CODCOLIGADA = 1.000000 AND A.CODCOMPRADOR = {codPlano}.000000 AND A.IDUNIDFAT = {codHospital}.000000 AND A.STATUSPROTOCOLO <> 'C' AND (TO_CHAR(A.DATAGERACAO, 'MM')|| '/' || TO_CHAR(A.DATAGERACAO, 'YYYY')  ) = '{entradaPeriodoMes.get()}/{entradaPeriodoAno.get()}' ORDER BY A.NUMEROREMESSA ASC;")
        global tables
        tables = int(cursor.fetchval())
        print(f"Foram encontradas {tables} ocorrências na página de faturas.")
        cursor.execute(f"SELECT NUMEROREMESSA FROM (SELECT ROW_NUMBER() OVER(ORDER BY NUMEROREMESSA ASC) AS Row#, CODCOLIGADA,CODCOMPRADOR, IDUNIDFAT, NUMEROLOTE, STATUSPROTOCOLO, NUMEROREMESSA FROM SZFATURACONVENIO WHERE CODCOLIGADA = 1.000000 AND CODCOMPRADOR = {codPlano}.000000 AND IDUNIDFAT = {codHospital}.000000 AND STATUSPROTOCOLO <> 'C' AND (TO_CHAR(DATAGERACAO, 'MM')|| '/' || TO_CHAR(DATAGERACAO, 'YYYY')  ) = '{entradaPeriodoMes.get()}/{entradaPeriodoAno.get()}' ) WHERE Row# = {entradaOrdemFatura.get()} ORDER BY NUMEROREMESSA ASC;")
        global fatura
        fatura = cursor.fetchval()
        print(fatura)
        #Marcar Fatura no sistema
        if entradaOrdemFatura.get() == '1':
            print("Fatura escolhida se encontra na primeira posição")
        elif entradaOrdemFatura.get() == '2':
            py.press('down')
        elif entradaOrdemFatura.get() == '3':
            py.press('down')
            py.press('down')
        elif entradaOrdemFatura.get() == '4':
            py.press('down')
            py.press('down')
            py.press('down')
        elif entradaOrdemFatura.get() == '5':
            py.press('down')
            py.press('down')
            py.press('down')
            py.press('down')
        #Tabela SZPARCIALATEND fornece os dados com total acurácia.
        cursor.execute(f"SELECT count(*) FROM RM.SZPARCIALATEND WHERE NUMEROREMESSA = {int(fatura)} AND CODCONVENIO = {codPlano} AND IDUNIDFAT = {codHospital};")
        global tables3
        tables3 = int(cursor.fetchval())
        print(f"{tables3} contas encontradas nessa fatura.")
    reconhecimento()
    contador = 0
    while contador != tables3:
        #Variável de Geração de Screenshots
        im = pyautogui.screenshot(f'imagens/image{contador}.png', region=(400,235,54,15))
        time.sleep(2)
        #Variável de processamento de imagens e obtenção de resultado para o sistema 100% testada e funcionando
        phrase = ocr.image_to_string(PIL.Image.open(f'imagens/image{contador}.png'), lang='por')
        print(f"O valor obtido foi de {phrase} reais.")
        if res.width == 1366 and res.height == 768:
            #Clique na seção de Contas
            py.moveTo(610,356)
            py.click()
            #Marcar conta no sistema
            if contador == 0:
                py.moveTo(467,458)
                py.doubleClick()
            elif contador == 1:
                py.moveTo(537,478)
                py.doubleClick()
            elif contador == 2:
                py.moveTo(537,495)
                py.doubleClick()
            elif contador == 3:
                py.moveTo(467,510)
                py.doubleClick()
            elif contador == 4:
                py.moveTo(479,527)
                py.doubleClick()
            elif contador == 5:
                py.moveTo(477,543)
                py.doubleClick()
            elif contador == 6:
                py.moveTo(454, 560)
                py.doubleClick()
            elif contador == 7:
                py.moveTo(479,578) 
                py.doubleClick()
            elif contador == 8:
                py.moveTo(474, 596)
                py.doubleClick()
            elif contador == 9:
                py.moveTo(469,612)
                py.doubleClick()
            elif contador == 10:
                py.moveTo(452,627)
                py.doubleClick()
            elif contador == 11:
                py.moveTo(466,644)
                py.doubleClick()
            elif contador == 12:
                py.moveTo(515, 645)
                py.click()
                py.press('down')
                py.doubleClick()
            elif contador == 13:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 14:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 15:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 16:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 17:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 18:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 19:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 20:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 21:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 22:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 23:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 24:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 25:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 26:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 27:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 28:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 29:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 30:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 31:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 32:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 33:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 34:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 35:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 36:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 37:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 38:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 39:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 40:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 41:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 42:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 43:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 44:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 45:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 46:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 47:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 48:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 49:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 50:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 51:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 52:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 53:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            elif contador == 54:
                py.moveTo(517, 645)
                py.click()
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.press('down')
                py.doubleClick()
            else:
                py.alert("Número de laços ainda não reconhecido.")
            title = "Registro de Recebimento por Conta"
            window = pygetwindow.getWindowsWithTitle(title)[0]
            if window.title == "Registro de Recebimento por Conta (RDESKAMB.UNIFESO.LAN)":
                #recebimento
                py.moveTo(479,147)
                py.click()
                #Clicar na data
                py.moveTo(412, 252)
                py.click()
                im1 = pyautogui.screenshot(f'valor/image{contador}.png', region=(618,193,60,16))
                time.sleep(4)
                phrase1 = ocr.image_to_string(PIL.Image.open(f'valor/image{contador}.png'), lang='por')
                #Recortar valor
                py.moveTo(494, 245)
                py.click()
                py.doubleClick()
                py.press('backspace')
                #Colar em Perda
                py.moveTo(493,291)
                py.doubleClick()
                py.press('backspace')
                replace = phrase1.replace(".","")
                print(replace)
                py.write(replace)
                #Gravando Processo no sistema
                py.press('tab')
                py.press('enter')
                #Último Processo 
                py.write('1')
                py.press('enter')
                #Saindo
                py.press('enter')
                py.press('enter')
                py.press('enter')
            time.sleep(18)
            title = "Erro"
            window = pygetwindow.getWindowsWithTitle(title)[0]
            if window.title == "Erro (RDESKAMB.UNIFESO.LAN)":
                try:
                    py.press('enter')
                except:
                    print('Tela de conclusão era requerida para continuar!')
                    exit()
            #Cancelando
            py.press('tab')
            py.press('tab')
            py.press('enter')
            fim = time.time()
            resultado = (fim - inicio)
            print(f"Duração de execução até aqui foi de {resultado: .2f} segundos. E a ordem desse paciente  é a {contador}.")
            contador = contador + 1
            #Laço de Repetição externo
        elif contador == tables3:
            py.moveTo(399,352)
            py.click()
            py.moveTo(349,444)
            py.click()
            py.press('down')
            if tables == 2:
                py.press('down')
                #for tabela in tables2:
            py.alert("Perdas efetuadas no sistema.")
            contador = contador - 1 
        else:
            py.alert("Resoluçao de tela não compatível com o sistema. Finalizando...")
            exit()

def recuperarLista():
    if Checkbutton1.get() == 1:
        baixa()
        exit()
    elif Checkbutton2.get() == 1:
        automacao()
        
btn = Button(window, text='Executar automação', command=recuperarLista, width=30, bg="#d3d3d3")
btn.place(x=90, y=140)

window.mainloop()

